# Generated by Django 4.0 on 2023-05-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
